<?php
function form_override_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['actions']['#attributes']['class'][] = 'element-invisible';
    $form['search_block_form']['#attributes']['placeholder'] = t('Search...');
        $form['first_name'] = array(
       '#type' => 'markup',
       '#prefix' => '<i class="icon-search nav-search-icon">',
       '#suffix' => '</i>',

    );
  }
  
   if (in_array( $form_id, array( 'user_login', 'user_login_block'))){
        $form['name']['#attributes']['placeholder'] = t( 'Username' );
        $form['pass']['#attributes']['placeholder'] = t( 'Password' );
        $form['name']['#title_display'] = "invisible"; 
        $form['pass']['#title_display'] = "invisible";
    }
}