<?php
function form_override_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['actions']['#attributes']['class'][] = 'element-invisible';
    $form['search_block_form']['#attributes']['placeholder'] = t('Search...');
        $form['first_name'] = array(
       '#type' => 'markup',
       '#prefix' => '<i class="icon-search nav-search-icon">',
       '#suffix' => '</i>',

    );
  }
  
  if ($form_id == 'user_login'){
        $form['name']['#attributes']['placeholder'] = t( 'Username' );
        $form['pass']['#attributes']['placeholder'] = t( 'Password' );
        $form['name']['#title_display'] = "invisible"; 
        $form['pass']['#title_display'] = "invisible";
        $form['name']['#description'] = "";
        $form['pass']['#description'] = "";
  }
  if ($form_id == 'user_register_form') {
    $form['account']['name']['#attributes']['placeholder'] = t( 'Username' );
    $form['account']['name']['#title_display'] = "invisible"; 
    $form['account']['name']['#description'] = ""; 
 
    $form['account']['mail']['#attributes']['placeholder'] = t( 'Email' );
    $form['account']['mail']['#title_display'] = "invisible"; 
    $form['account']['mail']['#description'] = "";
    
    //$form['account']['pass']['#attributes']['placeholder'] = t( 'Password' );
    //$form['account']['pass']['#type'] = ""; 
    $form['account']['pass']['#description'] = "";
  }
  //change comment button name
  if($form_id == 'comment_node_module_review_form') {
     $form['actions']['submit']['#value'] = t('Post'); // We have changed the label of the "Save" button on the comment form
  }
  
}