<?php
/**
 * @file
 * Implement socialshare support for Drupal
 */

/**
 * Implements hook_theme().
 */
function socialloginandsocialshare_share_theme() {
  return array(
    'socialloginandsocialshare_social_share' => array(
      'variables' => array(
        'node' => NULL,
        'position' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function socialloginandsocialshare_share_block_info() {
  $blocks['sharing'] = array(
    'info' => t('Social Sharing'),
  );
  return $blocks;
}

function socialloginandsocialshare_share_sharing_script() {
  drupal_add_js('//share.loginradius.com/Content/js/LoginRadius.js', array(
    'type' => 'external',
    'scope' => 'footer',
    'weight' => 5,
  ));
}

/**
 * Implements hook_block_view().
 */
function socialloginandsocialshare_share_block_view($delta) {
  if (!user_access('administer site configuration')) {
    $block = array();
    $output = '';
    if (variable_get('socialloginandsocialshare_enable_horizontal_share') == 1) {
      socialloginandsocialshare_horizontal_script_code();
      if (variable_get('socialloginandsocialshare_share_horizontal_images') == '0' || variable_get('socialloginandsocialshare_share_horizontal_images') == '1' || variable_get('socialloginandsocialshare_share_horizontal_images') == '2' || variable_get('socialloginandsocialshare_share_horizontal_images') == '3') {
        socialloginandsocialshare_share_sharing_script();
        $output .= '<div class="lrsharecontainer"></div>';
      }
      else {
        socialloginandsocialshare_share_sharing_script();
        $output .= '<div class="lrcounter_simplebox"></div>';
      }
    }
    if (variable_get('socialloginandsocialshare_enable_vertical_share') == 1) {
      socialloginandsocialshare_vertical_script_code();
      if (variable_get('socialloginandsocialshare_share_vertical_images') == '4' || variable_get('socialloginandsocialshare_share_vertical_images') == '5') {
        socialloginandsocialshare_share_sharing_script();
        $output .= '<div><div class="lrshareverticalcontainer"></div></div>';
      }
      else {
        socialloginandsocialshare_share_sharing_script();
        $output .= '<div><div class="lrcounter_verticalsimplebox"></div></div>';
      }
    }
    $block['content'] = $output;
    return $block;
  }
}

/**
 * Theme social share.
 */
function theme_socialloginandsocialshare_social_share($node) {
  $output = "";
  $item = menu_get_object($type = 'node', $position = 1, $path = NULL);
  $item = empty($item) ? menu_get_item() : $item;
  $item_nid = (!empty($item->nid) ? $item->nid : "");
  $item_title = (!empty($item->title) ? $item->title : "");
  $item_title = empty($item_title) && is_array($item) && isset($item['title']) ? $item['title'] : '';
  $shareall_withexcept = variable_get('socialshare_show_pages');
  $node_withexcept = variable_get('socialshare_show_exceptpages');
  $node_except = explode(',', $node_withexcept);
  $vertical_shareall_withexcept = variable_get('socialshare_vertical_show_pages');
  $vertical_node_withexcept = variable_get('socialshare_vertical_show_exceptpages');
  $vertical_node_except = explode(',', $vertical_node_withexcept);
  $selected_share_interface = variable_get('socialloginandsocialshare_selected_share_interface');
  $node_value = array_filter($node_except);
  $vertical_node_value = array_filter($vertical_node_except);
  if (variable_get('socialloginandsocialshare_enable_horizontal_share') == 1) {
    if ($node['position'] == 'horizontal') {
      if ($shareall_withexcept == 0) {
        if ((!in_array($item_nid, $node_except) && !in_array($item_title, $node_except)) || empty($node_value)) {
          if (variable_get('socialloginandsocialshare_share_horizontal_images') == '0' || variable_get('socialloginandsocialshare_share_horizontal_images') == '1' || variable_get('socialloginandsocialshare_share_horizontal_images') == '2' || variable_get('socialloginandsocialshare_share_horizontal_images') == '3') {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div class="lrsharecontainer"></div>';
          }
          else {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div class="lrcounter_simplebox"></div>';
          }
        }
      }
      elseif ($shareall_withexcept == 1) {
        if (in_array($item_nid, $node_except) OR in_array($item_title, $node_except)) {
          if (variable_get('socialloginandsocialshare_share_horizontal_images') == '0' || variable_get('socialloginandsocialshare_share_horizontal_images') == '1' || variable_get('socialloginandsocialshare_share_horizontal_images') == '2' || variable_get('socialloginandsocialshare_share_horizontal_images') == '3') {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div class="lrsharecontainer"></div>';
          }
          else {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div class="lrcounter_simplebox"></div>';
          }
        }
      }
    }
    socialloginandsocialshare_horizontal_script_code();
  }
  if (variable_get('socialloginandsocialshare_enable_vertical_share') == 1) {
    if ($node['position'] == 'vertical') {
      if ($vertical_shareall_withexcept == 0) {
        if ((!in_array($item_nid, $vertical_node_except) AND !in_array($item_title, $vertical_node_except)) || empty($vertical_node_value)) {
          if (variable_get('socialloginandsocialshare_share_vertical_images') == '4' || variable_get('socialloginandsocialshare_share_vertical_images') == '5') {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div><div class="lrshareverticalcontainer"></div></div>';
          }
          else {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div><div class="lrcounter_verticalsimplebox"></div></div>';
          }
        }
      }
      elseif ($vertical_shareall_withexcept == 1) {
        if (in_array($item_nid, $vertical_node_except) OR in_array($item_title, $vertical_node_except)) {
          if (variable_get('socialloginandsocialshare_share_vertical_images') == '4' || variable_get('socialloginandsocialshare_share_vertical_images') == '5') {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div><div class="lrshareverticalcontainer"></div></div>';
          }
          else {
            socialloginandsocialshare_share_sharing_script();
            $output .= '<div><div class="lrcounter_verticalsimplebox"></div></div>';
          }
        }
      }
    }
    socialloginandsocialshare_vertical_script_code();
  }
  return $output;
}

/**
 * Implements hook_node_view().
 */
function socialloginandsocialshare_share_node_view($node, $view_mode, $langcode) {
  if (!user_access('administer site configuration')) {
    if (variable_get('socialloginandsocialshare_enable_horizontal_share') == 1) {
      if (variable_get('socialshare_position_top', 1)) {
        $node->content['socialshare_top'] = array(
          '#markup' => theme('socialloginandsocialshare_social_share', array(
            'node' => $node,
            'position' => 'horizontal'
          )),
          '#weight' => -10,
        );
      }
      if (variable_get('socialshare_position_bottom', 1)) {
        $node->content['socialshare_bottom'] = array(
          '#markup' => theme('socialloginandsocialshare_social_share', array(
            'node' => $node,
            'position' => 'horizontal'
          )),
          '#weight' => 10,
        );
      }
    }
    if (variable_get('socialloginandsocialshare_enable_vertical_share') == 1) {
      $node->content['socialshare'] = array(
        '#markup' => theme('socialloginandsocialshare_social_share', array(
          'node' => $node,
          'position' => 'vertical'
        )),
        '#weight' => 10,
      );
    }

  }
}

/**
 *  Horizontal Social Sharing code.
 */
function socialloginandsocialshare_horizontal_script_code() {
//$selected_share_interface=variable_get('socialloginandsocialshare_selected_share_interface');
  $share_providers = variable_get("socialloginandsocialshare_rearrange_providers_list");
  if (empty($share_providers)) {
    variable_set('socialloginandsocialshare_rearrange_providers_list', array(
      "0" => "facebook",
      "1" => "googleplus",
      "2" => "google",
      "3" => "pinterest",
      "4" => "twitter",
    ));
  }
  if (variable_get('socialloginandsocialshare_share_horizontal_images') == '0' || variable_get('socialloginandsocialshare_share_horizontal_images') == '1' || variable_get('socialloginandsocialshare_share_horizontal_images') == '2' || variable_get('socialloginandsocialshare_share_horizontal_images') == '3') {
    $providers = implode(",", variable_get('socialloginandsocialshare_rearrange_providers_list'));
    if (variable_get('socialloginandsocialshare_share_horizontal_images') == '0' || variable_get('socialloginandsocialshare_share_horizontal_images') == '1') {
      $interface = 'horizontal';
    }
    else {
      $interface = 'simpleimage';
    }
    if (variable_get('socialloginandsocialshare_share_horizontal_images') == '0' || variable_get('socialloginandsocialshare_share_horizontal_images') == '2') {
      $size = '32';
    }
    else {
      $size = '16';
    }
    $api_key = trim(variable_get('socialloginandsocialshare_apikey'));
    $mysettings = array(
      'sharing' => TRUE,
      'lr_interface' => $interface,
      'providers' => $providers,
      'size' => $size,
      'apikey' => $api_key,
      'divwidget' => 'lrsharecontainer',
    );
  }
  else {
    $counter_providers = variable_get('socialcounter_rearrange_providers_list');
    if (empty($counter_providers)) {
      variable_set('socialcounter_rearrange_providers_list', array(
        "0" => "Facebook Like",
        "1" => "Google+ +1",
        "2" => "Pinterest Pin it",
        "3" => "LinkedIn Share",
        "4" => "Facebook Send",
      ));
    }
    $show_provider_list = array();
    $provider_list = variable_get('socialcounter_rearrange_providers_list');
    $providers = implode(",", $provider_list);
    if (variable_get('socialloginandsocialshare_share_horizontal_images') == '8' || variable_get('socialloginandsocialshare_share_horizontal_images') == '9') {
      $interface = 'simple';
    }
    if (variable_get('socialloginandsocialshare_share_horizontal_images') == '8') {
      $type = 'vertical';
    }
    else {
      $type = 'horizontal';
    }
    $mysettings = array(
      'counter' => TRUE,
      'lr_interface' => $interface,
      'providers' => $providers,
      'countertype' => $type,
      'divwidget' => 'lrcounter_simplebox',
    );
  }
  drupal_add_js(array('lrsocialshare' => $mysettings), 'setting');
  drupal_add_js($GLOBALS['base_url'] .'/'.drupal_get_path('module', 'socialloginandsocialshare') . '/js/socialshare_widget.js', array(
      'type' => 'external',
      'scope' => 'footer',
      'weight' => 7
    ));
}

/**
 *  Vertical Social Sharing code.
 */
function socialloginandsocialshare_vertical_script_code() {
  if (variable_get('socialloginandsocialshare_share_vertical_images') == '4' || variable_get('socialloginandsocialshare_share_vertical_images') == '5') {
    $share_providers = variable_get("socialshare_vertical_rearrange_providers_list");
    if (empty($share_providers)) {
      variable_set('socialshare_vertical_rearrange_providers_list', array(
        "0" => "facebook",
        "1" => "googleplus",
        "2" => "google",
        "3" => "pinterest",
        "4" => "twitter",
      ));
    }
    $providers = implode(",", variable_get('socialshare_vertical_rearrange_providers_list'));
    $interface = 'Simplefloat';
    if (variable_get('socialloginandsocialshare_share_vertical_images') == '4') {
      $size = '32';
    }
    else {
      $size = '16';
    }
    $api_key = trim(variable_get('socialloginandsocialshare_apikey'));
    if (variable_get('socialshare_vertical_position') == '0') {
      $position1 = 'top';
      $position2 = 'left';
    }
    elseif (variable_get('socialshare_vertical_position') == '1') {
      $position1 = 'top';
      $position2 = 'right';
    }
    elseif (variable_get('socialshare_vertical_position') == '2') {
      $position1 = 'bottom';
      $position2 = 'left';
    }
    else {
      $position1 = 'bottom';
      $position2 = 'right';
    }
    $mysettings = array(
      'verticalsharing' => TRUE,
      'lr_vertical_interface' => $interface,
      'vertical_providers' => $providers,
      'vertical_size' => $size,
      'vertical_apikey' => $api_key,
      'vertical_position1' => $position1,
      'vertical_position2' => $position2,
      'vertical_divwidget' => 'lrshareverticalcontainer',
    );
  }
  else {
    $counter_providers = variable_get('socialcounter_rearrange_providers_list');
    if (empty($counter_providers)) {
      variable_set('socialcounter_rearrange_providers_list', array(
        "0" => "Facebook Like",
        "1" => "Google+ +1",
        "2" => "Pinterest Pin it",
        "3" => "LinkedIn Share",
        "4" => "Facebook Send",
      ));
    }
    $provider_list = variable_get('socialcounter_vertical_rearrange_providers_list');
    $providers = implode(",", $provider_list);
    if (variable_get('socialloginandsocialshare_share_vertical_images') == '6') {
      $type = 'vertical';
    }
    elseif (variable_get('socialloginandsocialshare_share_vertical_images') == '7') {
      $type = 'horizontal';
    }
    if (variable_get('socialshare_vertical_position') == '0') {
      $position1 = 'top';
      $position2 = 'left';
    }
    elseif (variable_get('socialshare_vertical_position') == '1') {
      $position1 = 'top';
      $position2 = 'right';
    }
    elseif (variable_get('socialshare_vertical_position') == '2') {
      $position1 = 'bottom';
      $position2 = 'left';
    }
    else {
      $position1 = 'bottom';
      $position2 = 'right';
    }
    $mysettings = array(
      'verticalcounter' => TRUE,
      'vertical_providers' => $providers,
      'vertical_countertype' => $type,
      'vertical_position1' => $position1,
      'vertical_position2' => $position2,
      'vertical_divwidget' => 'lrcounter_verticalsimplebox',
    );
  }
  drupal_add_js(array('lrsocialshare' => $mysettings), 'setting');
  drupal_add_js($GLOBALS['base_url'] .'/'.drupal_get_path('module', 'socialloginandsocialshare') . '/js/socialshare_widget.js', array(
      'type' => 'external',
      'scope' => 'footer',
      'weight' => 7
    ));
}