# Schema for the configuration files of the Login shadowbox module.

login_shadowbox.settings:
  type: mapping
  label: 'Login shadowbox settings'
  mapping:
    login_shadowbox_enabled:
      type: boolean
      label: 'Enable shadowbox login'
    login_shadowbox_width:
      type: integer
      label: 'Shadowbox login width'
    login_shadowbox_height:
      type: integer
      label: 'Shadowbox login height'
    login_shadowbox_register_width:
      type: integer
      label: 'Shadowbox registration width'
    login_shadowbox_register_height:
      type: integer
      label: 'Shadowbox registration height'
    login_shadowbox_password_width:
      type: integer
      label: 'Shadowbox reset password width'
    login_shadowbox_password_height:
      type: integer
      label: 'Shadowbox reset password height'
    login_shadowbox_modal:
      type: boolean
      label: 'Shadowbox modal'
    login_shadowbox_css:
      type: string
      label: 'Shadowbox login css file'
