<?php
/*
* Implememnting hook_block_info
*/
function custom_block_block_info(){
     $blocks['Left-side-taxo-menu'] = array(
        'info' => t('Taxonomy menu'),
     );
      $blocks['user-profile'] = array(
        'info' => t('User profile'),
     );
return $blocks;
}
/*
* Implememnting hook_block_view
*/
function custom_block_block_view($delta = ''){
     $block = array();
          switch ($delta) {
               case 'Left-side-taxo-menu':
                  $block['subject'] = t('Taxonomy menu');
                  $block['content'] =  taxonomy_menu_block();
               break;
	       
	       case 'user-profile':
                  $block['subject'] = t('User profile');
                  $block['content'] =  user_profile_block();
               break;
          }
     return $block;
}
//taxonomy_menu_block
function taxonomy_menu_block(){
     global $base_url;
     $vocabulary=taxonomy_vocabulary_machine_name_load('left_side_taxo');
     $tree = taxonomy_get_tree($vocabulary->vid, $parent = 0, $max_depth = 1, $load_entities = FALSE);
     $taxo='<ul class="nav nav-list">';
     foreach ($tree as $term){
	  $page_url = drupal_lookup_path('alias',"taxonomy/term/".$term->tid);
	  $child_tax=taxonomy_get_children($term->tid);
	  if(!empty($child_tax)){
	       $taxo.='<li>
			 <a href="'.$page_url.'" class="dropdown-toggle">
			      <i class="icon-list"></i>
			      <span class="menu-text"> '.$term->name.' </span>
			      <b class="arrow icon-angle-down"></b>
			 </a>
			 <ul class="submenu">';
		    foreach($child_tax as $key=>$value){
			 $taxo.='<li>
				   <a href="'.$page_url.'">
					   <i class="icon-double-angle-right"></i>
					   '.$value->name.'
				   </a>
				 </li>';
		    }
			 $taxo.='</ul></li>';  
	  }else{
	       $taxo.='<li>
			 <a href="'.$page_url.'">
			       <i class="icon-list"></i>
			      <span class="menu-text"> '.$term->name.' </span>
			 </a>
		    </li>';
	  }
     }					
     $taxo.='</ul>';
     return $taxo;
}
//user profile block for top side
function user_profile_block(){
     global $user;
     if ($user->uid){
	  $user_profile=user_load($user->uid);
	  if(!empty($user_profile->picture)){
	       $user_img=theme_image_style(array('style_name'=>'36x36', 'path'=>$user_profile->picture->uri, 'width'=>'', 'height'=>'', 'alt'=>$user_profile->name, 'title'=>$user_profile->name, 'attributes' => array('class' => 'nav-user-photo')));
	  }else{
	       $user_img=theme("image", array('path' => path_to_theme().'/images/user.png',  'alt'=>$user_profile->name, 'title'=>$user_profile->name,  'width' => 36,    'height' => 36, 'attributes' => array('class' => 'nav-user-photo')));
	  }
	 $output='<li class="light-blue">
			 <a data-toggle="dropdown" href="#" class="dropdown-toggle">
				 '.$user_img.'
				 <span class="user-info">
					 <small>Welcome,</small>
					 '.ucfirst($user_profile->name).'
				 </span>
     
				 <i class="icon-caret-down"></i>
			 </a>
			 <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">';
			      
		    foreach(menu_get_names() as $menus){
			 if($menus=='main-menu'){
			      $menus_item=menu_load_links($menus);
			      foreach($menus_item as $menus_items){
				   $linktitle=$menus_items['link_title'];
				   $link_path=$menus_items['link_path'];
					      
				  $output.='<li>'.l($linktitle, $link_path, array('html' => TRUE)).' </li>';
				       
			      }
			 }
			       
		    }
		    $output.='</ul></li>';
	  return $output;
     }
     
}