<?php
/*
* Implememnting hook_block_info
*/
function custom_block_block_info(){
     $blocks['Left-side-taxo-menu'] = array(
        'info' => t('Taxonomy menu'),
     );
return $blocks;
}
/*
* Implememnting hook_block_view
*/
function custom_block_block_view($delta = ''){
     $block = array();
          switch ($delta) {
               case 'Left-side-taxo-menu':
                  $block['subject'] = t('Taxonomy menu');
                  $block['content'] =  taxonomy_menu_block();
               break;
          }
     return $block;
}
//taxonomy_menu_block
function taxonomy_menu_block(){
     global $base_url;
     $vocabulary=taxonomy_vocabulary_machine_name_load('left_side_taxo');
     $tree = taxonomy_get_tree($vocabulary->vid, $parent = 0, $max_depth = 1, $load_entities = FALSE);
     $taxo='<ul class="nav nav-list">';
     foreach ($tree as $term){
	  $page_url = drupal_lookup_path('alias',"taxonomy/term/".$term->tid);
	  $child_tax=taxonomy_get_children($term->tid);
	  if(!empty($child_tax)){
	       $taxo.='<li>
			 <a href="'.$page_url.'" class="dropdown-toggle">
			      <i class="icon-list"></i>
			      <span class="menu-text"> '.$term->name.' </span>
			      <b class="arrow icon-angle-down"></b>
			 </a>
			 <ul class="submenu">';
		    foreach($child_tax as $key=>$value){
			 $taxo.='<li>
				   <a href="'.$page_url.'">
					   <i class="icon-double-angle-right"></i>
					   '.$value->name.'
				   </a>
				 </li>';
		    }
			 $taxo.='</ul></li>';  
	  }else{
	       $taxo.='<li>
			 <a href="'.$page_url.'">
			       <i class="icon-list"></i>
			      <span class="menu-text"> '.$term->name.' </span>
			 </a>
		    </li>';
	  }
     }					
     $taxo.='</ul>';
     return $taxo;
}