# Schema for the configuration files of the Shadowbox module.

shadowbox.settings:
  type: mapping
  label: 'Shadowbox settings'
  mapping:
    shadowbox_location:
      type: string
      label: 'Shadowbox location'
    shadowbox_enabled:
      type: boolean
      label: 'Enable Shadowbox'
    shadowbox_activation_type:
      type: integer
      label: 'Enable Shadowbox on specific pages'
    shadowbox_pages:
      type: string
      label: 'Pages or PHP code'
    shadowbox_animate:
      type: boolean
      label: 'Enable animation'
    shadowbox_animate_fade:
      type: boolean
      label: 'Enable fading animationsn'
    shadowbox_animation_sequence:
      type: string
      label: 'Animation sequence'
    shadowbox_resize_duration:
      type: float
      label: 'Resize duration'
    shadowbox_fade_duration:
      type: float
      label: 'Fade duration'
    shadowbox_initial_height:
      type: integer
      label: 'Initial height'
    shadowbox_initial_width:
      type: integer
      label: 'Initial width'
    shadowbox_overlay_color:
      type: string
      label: 'Overlay color'
    shadowbox_overlay_opacity:
      type: float
      label: 'Overlay opacity'
    shadowbox_viewport_padding:
      type: integer
      label: 'Viewport padding'
    shadowbox_display_nav:
      type: boolean
      label: 'Display gallery navigation'
    shadowbox_continuous_galleries:
      type: boolean
      label: 'Enable continuous galleries'
    shadowbox_display_counter:
      type: boolean
      label: 'Enable counter'
    shadowbox_counter_type:
      type: string
      label: 'Counter type'
    shadowbox_counter_limit:
      type: integer
      label: 'Counter limit'
    shadowbox_slideshow_delay:
      type: integer
      label: 'Slideshow delay'
    shadowbox_autoplay_movies:
      type: boolean
      label: 'Auto-play movies'
    shadowbox_show_movie_controls:
      type: boolean
      label: 'Enable movie controls'
    shadowbox_youtube_quality:
      type: string
      label: 'Youtube Quality'
    shadowbox_overlay_listen:
      type: boolean
      label: 'Mouse click closes overlay'
    shadowbox_enable_keys:
      type: boolean
      label: 'Enable keys'
    shadowbox_handle_oversize:
      type: string
      label: 'Handle large images'
    shadowbox_handle_unsupported:
      type: string
      label: 'Handle unsupported'
    shadowbox_use_sizzle:
      type: boolean
      label: 'Use Sizzle'

shadowbox.automatic:
  type: mapping
  label: 'Shadowbox automatic settings'
  mapping:
    shadowbox_auto_enable_all_images:
      type: boolean
      label: 'Enable for all image links'
    shadowbox_auto_gallery:
      type: boolean
      label: 'Group images as a shadowbox gallery'
    shadowbox_enable_globally:
      type: boolean
      label: 'Enable shadowbox globally'